### ISSUE TITLE
sending data / using processing time even when no client is connected

### ISSUE THREAD

**Issue by rejuce** [JPery/MJPEGWriter#8]
i compiled it and i works, great idea and was exactly what i was looking for. I could stream frames coming from hardware to firefox / vlc.

i noticed though that as soon as its started, it takes up a lot of processing time (from looking over the code it seems the load comes from the Writer) which keeps writing even when no client is yet connected / or the last client disconnected

would it not be better if it starts writing  only after at least one client is connected (and stops after the last disconnects)?
 If no client is connected just Listen and wait until one connects or is there smt that would stand against that?

**Comment by JPery** [comment]
I've done a modification to the Writer code. Now it only uses ~10% of CPU compared to the previous ~70% when no client is connected. Tell me if u can test it.

**Comment by rejuce** [comment]
currently i dont have time to test it but the change in the code looks good, it should work now
you called the variablede milis2wait while its actually µS. thank you, i let you know once i have tested it in the future

**Comment by starrabb1t** [comment]
@JPery , what hardware do you have? 

On my RPi 3 it uses about 50% of all cores to compare with [mjpg_streamer](https://github.com/jacksonliam/mjpg-streamer/tree/master/mjpg-streamer-experimental), that uses only 10-20%. However, your implementation works much better.

**Comment by JPery** [comment]
Hi, @starrabb1t 
I'm testing the library in an Intel Core i7 4790HQ.

The processing time of the library is mostly due to the JPEG encoding. You can reduce the JPEG quality (now is 90) to a lower value in order to reduce this processing time. You can change this value [here](https://github.com/JPery/MJPEGWriter/blob/a2ee0159ab8c88a1bffad3ef035426db0d4ec41d/MJPEGWriter.h#L109).

The other consuming task is that the library is streaming 60 FPS (also encoding to JPEG 60 times per second). You can also reduce this (to 25 for example) in order to also reduce the processing time. This can be changed [in this line](https://github.com/JPery/MJPEGWriter/blob/a2ee0159ab8c88a1bffad3ef035426db0d4ec41d/MJPEGWriter.cpp#L63), changing this value (1000000/60) to, for example, 40000 (25 FPS)

Hope this helps.
Best regards
